export enum TfaAction {
    SIGN_IN = "SIGN_IN",
    SIGN_UP = "SIGN_UP",
    RECOVER_PASSWORD = "RECOVER_PASSWORD",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    UPDATE_EMAIL = "UPDATE_EMAIL",
    UPDATE_PASSWORD = "UPDATE_PASSWORD"
}